image: node:latest

services:
  - mysql:latest
  
stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
   
cache:
  paths:
    - node_modules/

unit_test:
  stage: test
  script:
    - npm run test-unit

integration_test:
  stage: test
  script:
    - npm run test-integration
