image: node:lts-alpine3.9

services:
  - mysql:latest
  
stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - apk add --no-cache python make g++
    - npm install
    - npm rebuild
   
cache:
  paths:
    - node_modules/

unit_test:
  stage: test
  script:
    - npm run test-unit

integration_test:
  stage: test
  script:
    - npm run test-integration
